receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  otlp:
    endpoint: https://otlp.nr-data.net:443
    headers:
      api-key: NEW_RELIC_LICENSE_KEY

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]
      processors: [batch]